### ISSUE TITLE
SFDX complains NPM is not Installed

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/sfdx-plugin-lwc-test#13]
My npm is properly installed but sfdx keeps showing this message:
![image](https://user-images.githubusercontent.com/55927613/81823003-b9b4fd00-952b-11ea-9bf0-cbd2f785af35.png)

**Comment by pmdartus** [comment]
This is a duplicate of https://github.com/salesforce/sfdx-plugin-lwc-test/issues/9
