### ISSUE TITLE
Cannot install lwc/rest/jest

### ISSUE THREAD

**Issue by architectonicus** [salesforce/sfdx-plugin-lwc-test#9]
Trying to install via cli setup:

>sfdx force:lightning:lwc:test:setup --loglevel debug
ERROR running force:lightning:lwc:test:setup:  npm command not found. Verify npm is properly installed and try again.

Running npm shows:
npm@6.9.0 C:\Program Files\nodejs\node_modules\npm

**Comment by trevor-bliss** [comment]
Could you please provide more info about the environment you're running the command in? From your post it looks like you're on Windows. Is that being run in the standard Windows Command Prompt?

**Comment by architectonicus** [comment]
Running on Windows 10 Enterprise. VisualStudioCode also installed and CLI working without problems. I'm behind a restrictive corporate firewall, but that hat nothing to do with the problem at hand.
In [setup.ts](https://github.com/salesforce/sfdx-plugin-lwc-test/blob/master/src/commands/force/lightning/lwc/test/setup.ts) the following seems to be failing:
```
 const npmVersionRet = spawnSync('npm', ['-v']);
    if (npmVersionRet.error || npmVersionRet.status !== 0) {
      throw new SfdxError(messages.getMessage('errorNpmNotFound'));
    }
```
Note that
>npm -v
6.9.0

**Comment by pmdartus** [comment]
It looks like `npm -v` fails when ran via `spawnSync` on your machine. This is strange since you also mention that running `npm -v` command directly in the console is successful. 

Could you please patch the code locally, to log the value of `npmVersionRet`, so would help us investigate. I am wondering what is reported in `stdout`, `stderr,` `error` and `status`.

**Comment by architectonicus** [comment]
Unfortunately I'm not coding, so I can't patch it locally. I tried a simple script:
`var runSync = require('child_process').spawnSync;
const npmVersionRet = runSync('npm', ['-v']);`

which returns:
`{ error:
   { Error: spawnSync npm ENOENT
       at Object.spawnSync (internal/child_process.js:1002:20)
       at spawnSync (child_process.js:614:24)
       at Object.<anonymous> (C:\Users\***\sf-org\testsync.js:2:23)
       at Module._compile (internal/modules/cjs/loader.js:778:30)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
       at Module.load (internal/modules/cjs/loader.js:653:32)
       at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
       at Function.Module._load (internal/modules/cjs/loader.js:585:3)
       at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
       at startup (internal/bootstrap/node.js:283:19)
     errno: 'ENOENT',
     code: 'ENOENT',
     syscall: 'spawnSync npm',
     path: 'npm',
     spawnargs: [ '-v' ] },
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null }
{ Error: spawnSync npm ENOENT
    at Object.spawnSync (internal/child_process.js:1002:20)
    at spawnSync (child_process.js:614:24)
    at Object.<anonymous> (C:\Users\****\***\sf-org\testsync.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawnSync npm',
  path: 'npm',
  spawnargs: [ '-v' ] }
null`

Not sure if this helps. Also, have a look at [this problem](https://stackoverflow.com/questions/37125619/spawnsyncnpm-install-gives-error-spawnsync-npm-enoent). Of course, it's not the same code as in the test, but it might be a hint.

**Comment by trevor-bliss** [comment]
@architectonicus you're not using Git Bash instead of the Windows Command Prompt are you?

I wonder if we need to pass in `{ shell: true }` or use `execSync` instead of `spawnSync` like discussed in this issue: https://github.com/nodejs/help/issues/728

**Comment by architectonicus** [comment]
@trevor-bliss , nope, I use the powershell most of the time. If not, I use the Terminal inside VisualStudioCode. The "classic" windows console behaves for me just like power shell or the VSC terminal.

I tried execSync and also shell: true. In these cases my script doesn't return.
 
This produces an output, though:
`
var runSync = require('child_process').spawnSync;
const npmVersionRet = runSync('npm', ['--version'],{shell: true, stdio: [0, 1, 2] });
console.log(`hello node`);
console.log(npmVersionRet)
console.log(npmVersionRet.error)
console.log(npmVersionRet.status);
`
Prints:
`
6.9.0
hello node
{ status: 0,
  signal: null,
  output: [ null, null, null ],
  pid: 16296,
  stdout: null,
  stderr: null }
undefined
0
`
Picked up from [here](https://github.com/nodejs/node-v0.x-archive/issues/25330).

**Comment by trevor-bliss** [comment]
Interesting. Changing the check from `spawnSync('npm', ['-v'])` to  `spawnSync('npm', ['-v'], { shell: true, stdio: [0, 1, 2] })` sounds reasonable to me.

Any concerns @pmdartus?

**Comment by pmdartus** [comment]
This issue is from 2015, and the child process builtin module changed a lot since then, so I wouldn't recommend following if we are not 100% certain of what we are doing.

The `stdio` is unrelated to the issue until proven otherwise. The default value pipes the results out. The `[0, 1, 2]` is equivalent to `inherit` which would print out the command output to the parent process output which is undesirable in the case of the CLI.

Concerning the `shell` flag, this flag is false by default on the `spawnSync` which is probably the root of the problem. Going through the documentation of the [child process module](https://nodejs.org/dist/latest-v12.x/docs/api/child_process.html), this module also exposes wrapper methods for common use cases. Based on the documentation, I would recommend swapping `spawnSync('npm', ['-v'])` with `execSync('npm', ['-v'])` that spawn a new shell automatically.

**Comment by architectonicus** [comment]
“I would recommend swapping spawnSync('npm', ['-v']) with execSync('npm', ['-v']) that spawn a new shell automatically.”

Please note that the execSync as executed in my test script never returns.

**Comment by pmdartus** [comment]
I found the issue, the `execSync` method doesn't accept the argument a second parameter. It should be `execSync('npm -v'])` and not `execSync('npm', ['-v'])`. I tried on a Windows VM and it works. 

@architectonicus Could you confirm you also observe the same thing?

**Comment by architectonicus** [comment]
@pmdartus I observe the same. `execSync('npm -v')` works for me.
